#!/bin/bash
# =============================================================================
# Install per-channel systemd metrology units
# =============================================================================
# Replaces the old monolithic timestd-metrology.service (forking shell script)
# with individual timestd-metrology@CHANNEL.service template instances.
#
# Each channel gets:
#   - Independent restart on crash/OOM
#   - Memory limits (MemoryMax=1200M)
#   - OOM protection (OOMScoreAdjust=-500)
#   - Proper systemd status visibility
#
# Usage: sudo bash deploy/systemd/install-metrology-units.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="/etc/hf-timestd/timestd-config.toml"
ENV_DIR="/etc/hf-timestd/metrology-channels"
SYSTEMD_DIR="/etc/systemd/system"

# All 9 channels
CHANNELS=(
    SHARED_2500
    SHARED_5000
    SHARED_10000
    SHARED_15000
    WWV_20000
    WWV_25000
    CHU_3330
    CHU_7850
    CHU_14670
)

# Channel -> frequency_hz mapping
declare -A FREQ_MAP=(
    [SHARED_2500]=2500000
    [SHARED_5000]=5000000
    [SHARED_10000]=10000000
    [SHARED_15000]=15000000
    [WWV_20000]=20000000
    [WWV_25000]=25000000
    [CHU_3330]=3330000
    [CHU_7850]=7850000
    [CHU_14670]=14670000
)

echo "=== Installing per-channel metrology systemd units ==="

# --- Parse station config from TOML ---
if [ ! -f "$CONFIG" ]; then
    echo "ERROR: Config not found: $CONFIG"
    exit 1
fi

CALLSIGN=$(grep '^callsign' "$CONFIG" | head -1 | cut -d'"' -f2)
GRID_SQUARE=$(grep '^grid_square' "$CONFIG" | head -1 | cut -d'"' -f2)
STATION_ID=$(grep '^id' "$CONFIG" | head -1 | cut -d'"' -f2)
INSTRUMENT_ID=$(grep '^instrument_id' "$CONFIG" | head -1 | cut -d'"' -f2)
LATITUDE=$(grep '^latitude' "$CONFIG" | head -1 | awk '{print $3}')
LONGITUDE=$(grep '^longitude' "$CONFIG" | head -1 | awk '{print $3}')
DATA_ROOT=$(grep '^production_data_root' "$CONFIG" | head -1 | cut -d'"' -f2)
DATA_ROOT="${DATA_ROOT:-/var/lib/timestd}"

# Check tiered storage
TIERED=$(grep '^tiered_storage' "$CONFIG" | head -1 | awk '{print $3}')
if [ "$TIERED" = "true" ]; then
    ARCHIVE_ROOT="/dev/shm/timestd/raw_buffer"
else
    ARCHIVE_ROOT="$DATA_ROOT/raw_buffer"
fi

echo "  Station: $CALLSIGN ($STATION_ID)"
echo "  Grid:    $GRID_SQUARE"
echo "  Coords:  ${LATITUDE}°N, ${LONGITUDE}°W"
echo "  Data:    $DATA_ROOT"
echo "  Archive: $ARCHIVE_ROOT"
echo ""

# --- Generate per-channel environment files ---
mkdir -p "$ENV_DIR"

for ch in "${CHANNELS[@]}"; do
    freq_hz="${FREQ_MAP[$ch]}"
    cat > "$ENV_DIR/${ch}.env" << EOF
# Auto-generated by install-metrology-units.sh
# Channel: $ch
FREQUENCY_HZ=$freq_hz
CALLSIGN=$CALLSIGN
GRID_SQUARE=$GRID_SQUARE
STATION_ID=$STATION_ID
INSTRUMENT_ID=$INSTRUMENT_ID
LATITUDE=$LATITUDE
LONGITUDE=$LONGITUDE
DATA_ROOT=$DATA_ROOT
ARCHIVE_ROOT=$ARCHIVE_ROOT
EOF
    echo "  Created $ENV_DIR/${ch}.env"
done

# --- Install systemd units ---
echo ""
echo "Installing systemd units..."

# Stop old monolithic service if running
if systemctl is-active --quiet timestd-metrology.service 2>/dev/null; then
    echo "  Stopping old timestd-metrology.service..."
    systemctl stop timestd-metrology.service
    sleep 2
fi

# Also kill any orphaned workers from the old script
pkill -f "hf_timestd.core.metrology_service" 2>/dev/null || true
sleep 1

# Copy unit files
cp "$SCRIPT_DIR/timestd-metrology@.service" "$SYSTEMD_DIR/"
cp "$SCRIPT_DIR/timestd-metrology.target" "$SYSTEMD_DIR/"
cp "$SCRIPT_DIR/timestd-raw-cleanup.service" "$SYSTEMD_DIR/"
cp "$SCRIPT_DIR/timestd-raw-cleanup.timer" "$SYSTEMD_DIR/"

# Disable old monolithic service
systemctl disable timestd-metrology.service 2>/dev/null || true

# Reload and enable
systemctl daemon-reload

# Enable target
systemctl enable timestd-metrology.target

# Enable raw buffer cleanup timer (daily, keeps 3 days)
systemctl enable --now timestd-raw-cleanup.timer
echo "  Enabled timestd-raw-cleanup.timer (daily at 02:30 UTC, keeps 3 days)"

# Enable and start each channel
for ch in "${CHANNELS[@]}"; do
    systemctl enable "timestd-metrology@${ch}.service"
    echo "  Enabled timestd-metrology@${ch}"
done

echo ""
echo "Starting all channels..."
for ch in "${CHANNELS[@]}"; do
    systemctl start "timestd-metrology@${ch}.service"
    sleep 0.5
done

# Wait for startup
sleep 3

echo ""
echo "=== Status ==="
for ch in "${CHANNELS[@]}"; do
    status=$(systemctl is-active "timestd-metrology@${ch}.service" 2>/dev/null || echo "unknown")
    printf "  %-20s %s\n" "$ch" "$status"
done

RUNNING=$(systemctl list-units "timestd-metrology@*" --state=running --no-legend 2>/dev/null | wc -l)
echo ""
echo "✅ $RUNNING/9 channels running"
echo ""
echo "Useful commands:"
echo "  systemctl status timestd-metrology@SHARED_15000"
echo "  journalctl -u timestd-metrology@SHARED_15000 -f"
echo "  systemctl restart timestd-metrology@CHU_7850"
echo "  systemctl list-units 'timestd-metrology@*'"
