#!/bin/bash
# setup-cpu-affinity.sh - Configure CPU affinity for radiod and hf-timestd
#
# This script:
# 1. Detects the number of CPU cores
# 2. Creates a systemd drop-in to pin radiod to the top 2 cores
# 3. Ensures hf-timestd processes yield to radiod
#
# Usage: sudo ./setup-cpu-affinity.sh [radiod-instance-name]
# Example: sudo ./setup-cpu-affinity.sh ac0g-bee1-rx888

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get radiod instance name from argument or detect it
RADIOD_INSTANCE="${1:-}"

if [ -z "$RADIOD_INSTANCE" ]; then
    # Try to detect running radiod instance
    RADIOD_INSTANCE=$(systemctl list-units --type=service --state=running | grep 'radiod@' | sed 's/.*radiod@\([^.]*\).*/\1/' | head -1)
    if [ -z "$RADIOD_INSTANCE" ]; then
        echo -e "${YELLOW}No running radiod instance detected.${NC}"
        echo "Usage: $0 <radiod-instance-name>"
        echo "Example: $0 ac0g-bee1-rx888"
        exit 1
    fi
    echo -e "${GREEN}Detected radiod instance: ${RADIOD_INSTANCE}${NC}"
fi

# Detect CPU count
NPROC=$(nproc)
echo -e "${GREEN}Detected ${NPROC} CPU cores${NC}"

# Calculate upper half of cores for radiod (e.g., cores 8-15 on 16-core system)
# This allows Linux scheduler to distribute radiod's 40+ threads efficiently
HALF_CORES=$((NPROC / 2))
UPPER_CORES=$(seq -s ' ' $HALF_CORES $((NPROC - 1)))

echo -e "${GREEN}Assigning radiod to upper half of CPU: cores ${HALF_CORES}-$((NPROC - 1))${NC}"

# Create drop-in directory for radiod instance
DROPIN_DIR="/etc/systemd/system/radiod@${RADIOD_INSTANCE}.service.d"
echo "Creating drop-in directory: ${DROPIN_DIR}"
mkdir -p "$DROPIN_DIR"

# Create the drop-in file
DROPIN_FILE="${DROPIN_DIR}/cpu-affinity.conf"
cat > "$DROPIN_FILE" << EOF
# Auto-generated by hf-timestd setup-cpu-affinity.sh
# Pins radiod to upper half of CPU cores for real-time USB/FFT processing
# Allows Linux scheduler to distribute 40+ radiod threads efficiently across multiple cores
# Generated: $(date -Iseconds)

[Service]
# Pin to upper half: cores ${HALF_CORES}-$((NPROC - 1)) (upper half of ${NPROC} cores)
CPUAffinity=${UPPER_CORES}

# High priority for real-time audio processing
Nice=-15
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=80
EOF

echo -e "${GREEN}Created ${DROPIN_FILE}${NC}"

# Reload systemd
echo "Reloading systemd daemon..."
systemctl daemon-reload

# Show status
echo ""
echo -e "${GREEN}CPU affinity configured successfully!${NC}"
echo ""
echo "To apply changes, restart radiod:"
echo "  sudo systemctl restart radiod@${RADIOD_INSTANCE}"
echo ""
echo "To verify CPU affinity after restart:"
echo "  taskset -cp \$(pgrep -f radiod)"
echo ""
echo "hf-timestd services are configured with Nice=5 to yield to radiod."
